Sage-Bionetworks/snowflake

synapse_data_warehouse/synapse_raw/tables/V2.10.0__add_session_id_to_filedownloads.sql
synapse_data_warehouse/synapse_raw/tasks/V2.10.1__add_session_id_to_filedownload_tasks.sql

Add session id column for file download records

[SNOW-38] Add session id for file download records

---

synapse_data_warehouse/synapse_raw/tables/V2.12.0__add_snapshot_date_to_fileinventory.sql

Add snapshot date

---

admin/grants.sql
admin/users.sql

Add CNB users to snowflake and grant data analytics role

Add in cnb users

---

synapse_data_warehouse/synapse_raw/tasks/V2.13.3__escape_new_line_nodesnapshots.sql

Problem:
```
100069 (22P02): Error parsing JSON: unterminated string, line 2, pos 0
```
There are annotations that have the string `'\n'`.
Solution:
Escaping new line

[SNOW-61] Escape new line for annotations

---

synapse_data_warehouse/synapse/tables/V2.19.0__add_table_file_latest_comments.sql

**Problem:**
1. No comments were present on the FILE_LATEST table
**Solution:**
1. Creating a SQL script to add comments to the columns

[SNOW-79] Add comments to the columns of the file_latest table

---

synapse_data_warehouse/synapse/tables/V2.19.0__add_table_file_latest_comments.sql

Correct the column names
**Problem:**
1. No comments were present on the FILE_LATEST table
**Solution:**
1. Creating a SQL script to add comments to the columns

[SNOW-79] Create V2.19.0__add_table_file_latest_comments.sql

---

synapse_data_warehouse/synapse/tables/V2.19.5__correct_userprofile_latest_comments.sql

**Problem:**
1. 3 Column descriptions differ from their expected values.
2. https://github.com/Sage-Bionetworks/snowflake/issues/59
**Solution:**
1. Updated the column description for the 3 columns.

[Issue-59] Correct description of userprofile latest

---

streamlit_template/.streamlit/config.toml
streamlit_template/app.py
streamlit_template/style.css
streamlit_template/toolkit/queries.py
streamlit_template/toolkit/widgets.py

Revert changes to Streamlit app template that were meant for a fork

Revert streamlit changes

---

synapse_data_warehouse/synapse_raw/tables/V2.25.2__refresh_node_snapshot.sql

During the CI workflow, I saw this error. These changes attempt to avoid this issue by avoiding the mixing of variable scopes by defining all variables within the Snowflake scripting block.
```
Traceback (most recent call last):
schemachange version: 3.6.1
File "/opt/hostedtoolcache/Python/3.10.15/x64/bin/schemachange", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/schemachange/cli.py", line 896, in main
Using config file: synapse_data_warehouse/schemachange-config.yml
Using root folder /home/runner/work/snowflake/snowflake/synapse_data_warehouse
Using variables:
database_name: SYNAPSE_DATA_WAREHOUSE_DEV
stage_storage_integration: synapse_dev_warehouse_s3
stage_url: s3://dev.datawarehouse.sagebase.org/warehouse/
stack: dev …
```

[SNOW-160] Simplify refresh node snapshot

---

admin/grants.sql
admin/users.sql

Add jo scanlan and grant to data analytics role

---

admin/grants.sql
admin/users.sql

Add Trish Zintel to ADTR users & grant `DATA_ANALYTICS` role to user

Add Trish Zantel to ADTR users & grant `DATA_ANALYTICS`

---

admin/grants.sql
admin/users.sql

Add Privacy & Compliance Team to Snowflake

---

admin/grants.sql
admin/users.sql

* add Christine, Anthony, Hayley as users
* Update grants.sql
* remove redundancy grant
* move users to Governance

Cherry pick commit for Privacy & Compliance Team to Snowflake (PR #120)

---

admin/grants.sql
admin/users.sql

Adding new user directly to `main` (avoids the cherry-picking)

Add Bishoy to prod

---

admin/grants.sql
admin/users.sql

Grant Andrea our COO to Snowflake and DATA_ANALYTICS role
I'm pointing to `dev` from our agreement that everything will flow through `dev` now, even admin commands.

[SNOW-248] Add Andrea to `DATA_ANALYTICS` users

---

synapse_data_warehouse/database_roles/V2.44.0__drop_all_admin_database_role.sql

See [ticket](https://sagebionetworks.jira.com/browse/SNOW-249) for problem description.

[SNOW-249] Drop unused database role ALL_ADMIN

---

admin/users.sql

See [ticket](https://sagebionetworks.jira.com/browse/SNOW-241) for problem description.
I add a scripting block to `admin/users.sql` which loops over all users in our account, and if their DEFAULT_SECONDARY_ROLES property is set to one of:
* `''` (empty string)
* `<null>`
* `["ALL"]`
then we update the user so that their DEFAULT_SECONDARY_ROLES is set to `[]`. In most cases, this block will only have an effect initially (since default secondary roles is currently enabled for most users) or when we create a new user (in which case Snowflake automatically creates that user with default secondary roles enabled).

[SNOW-241] Disable secondary roles by default for all users

---

admin/grants.sql
admin/users.sql

Doing this as a PR rather than a cherry-pick so that we get a merge commit.

[SNOW-248] Add Andrea to `DATA_ANALYTICS` users (#164)

---

.github/pull_request_template.md

Ticket: [DPE-1253](https://sagebionetworks.jira.com/browse/DPE-1253)
1. All DPE repositories have PR templates
* I didn't do this for all DPE repositories, but I'm doing it now for the snowflake repository, as you can see [here](https://github.com/Sage-Bionetworks/snowflake/blob/634ee0baf65468e69d12f77d3a3375b3bbf425c1/.github/pull_request_template.md).
Since Snowflake PRs are heavily developer-oriented, I modified the instructions under each heading to better complement the information we already provide for developers in Jira.
I also streamlined the formatting and specified all template instructions in `` so that we don't need to manually overwrite them with each PR. You can see this for yourself by clicking the dropdown for this PR description and choosing "edit". All of the template …

[DPE-1253] Add PR template

---

admin/users.sql

Finance team need to be added and people who have left sage can be removed.
Added the finance team
NA
This is an exception to fast track adding users to PR into `main`

Add finance users

---

.github/actions/configure-snowflake-cli/action.yml
.github/pull_request_template.md
.github/workflows/ci.yaml
admin/integrations.sql
synapse_data_warehouse/database_roles/V2.44.0__drop_all_admin_database_role.sql

Adds commits:
* daa003a (#162)
* 42efb8a (#157)
* 4eca67a (#169)

Merge dev to main

---

.github/workflows/ci.yaml

Snowflake CLI could not find the passphrase because it was not included in the environment variables.
For some reason, Snowflake CLI does not utilize the `private_key_file_pwd` parameter in the connections.toml file (although it _does_ use this file). Instead we need to include this variable in a `PRIVATE_KEY_PASSPHRASE` environment variable. 
This is what I did in `.github/actions/configure-snowflake-cli/action.yml` when I test that the Snowflake CLI is set up correctly:
https://github.com/Sage-Bionetworks/snowflake/blob/4eca67aae11f624f844b2359268b4fdc6cf2fa3f/.github/actions/configure-snowflake-cli/action.yml#L99-L109

Include passphrase in env for Snowflake CLI

---

admin/users.sql

Our [latest CI deployment](https://github.com/Sage-Bionetworks/snowflake/actions/runs/13999369618/job/39202148530) failed because we try to create a user which already exists. Snowflake does not realize that this user already exists because user names are case-insensitive, but the `IF EXISTS` logic doesn't account for this.
This user is special, since they are owned by the `GENERIC_SCIM_PROVISIONER` role, and not the usual `USERADMIN` role. I think this is because they were provisioned via Jumpcloud. This repo is not the domain to manage these kinds of users, so we've commented this user out.
Nah.

Comment out user creation

---

admin/integrations.sql

The [previous CI run](https://github.com/Sage-Bionetworks/snowflake/actions/runs/14001491450/job/39208679209) failed because `admin/integrations.sql` contained a `snowsql` client-specific command which was formerly necessary for variable substitution.
The new Snowflake CLI natively supports variable substitution, so I removed this command.

Remove snowsql variable substitue indicator

---

admin/grants.sql

The [previous CI run](https://github.com/Sage-Bionetworks/snowflake/actions/runs/14001894809/job/39209878662) did not succeed because of more case-sensitive user name shenanigans.
I fixed the casing and I did not find any other instances where this user was referenced incorrectly.
I ran this command as SECURITYADMIN in a worksheet and it succeeded.

Fix casing of user name

---

synapse_data_warehouse/synapse/tables/R__my_table.sql

Ticket: [SNOW-404](https://sagebionetworks.jira.com/browse/SNOW-404-fake)
1. My first acceptance criteria
* How I addressed this in [these lines of code](https://github.com/Sage-Bionetworks/snowflake/pull/404/files#diff-shaR1-R100)

Snow 90 ci cd test merge

---

CONTRIBUTING.md

Ticket: [SNOW-404](https://sagebionetworks.jira.com/browse/SNOW-404-fake)
1. My first acceptance criteria
* How I addressed this in [these lines of code](https://github.com/Sage-Bionetworks/snowflake/pull/404/files#diff-shaR1-R100)

necessary changes to docs

---

admin/grants.sql
admin/users.sql

> NOTE, this is a merge directly into `main`
Serghei does not have access to snowflake, and we would like his input on the data re-use strategy at sage.
Ticket: https://sagebionetworks.jira.com/browse/SNOW-273
Add him
N/A

[SNOW-273] Add Serghei into snowflake

---

admin/grants.sql
admin/users.sql

Some people required access. NOTE: This is a direct push into main
Ticket: Did not have a ticket
Add users to snowflake
1. My first acceptance criteria
* How I addressed this in [these lines of code](https://github.com/Sage-Bionetworks/snowflake/pull/404/files#diff-shaR1-R100) 
NA

Add users to snowflake

---

admin/grants.sql
admin/users.sql

Ann requires the ability to query the ADTR dashboard within snowflake
Ticket: [SNOW-264](https://sagebionetworks.jira.com/browse/SNOW-264)
Provide Ann DATA ANALYTICS role
NOTE: This is a direct push into the `main` branch
[SNOW-264]: https://sagebionetworks.jira.com/browse/SNOW-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SNOW-264] Add User

---

synapse_data_warehouse/synapse_event/dynamic_tables/V2.61.0__update_node_event_window.sql

Ticket: [SNOW-316](https://sagebionetworks.jira.com/browse/SNOW-316)
Depends on #231 
1. determine why node_event doesn't seem to capture these events
* We don't capture updates to data because we currently keep the very first snapshot associated with an event. The only change made in this PR is to keep the most recent snapshot instead. See [this comment](https://sagebionetworks.jira.com/browse/SNOW-316?focusedCommentId=259692) for more details.
2. Create a ticket to fix the issue if it's requires much more exploration
* not applicable 
[SNOW-316]: https://sagebionetworks.jira.com/browse/SNOW-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SNOW-316] Capture most recent snapshot of node events

---

admin/grants.sql
admin/users.sql

Savitha does not have access to the Snowflake space
Ticket: [DPESPRT-305](https://sagebionetworks.jira.com/browse/DPESPRT-305)
Grant Savitha access to Snowflake to pull MC2 metrics
NA
[DPESPRT-305]: https://sagebionetworks.jira.com/browse/DPESPRT-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DPESPRT-305] Add Savitha to Snowflake

---

synapse_data_warehouse/synapse/dynamic_tables/V2.63.11__certifiedquizquestion_latest_date_comparison_fixed.sql

Ticket: [SNOW-336](https://sagebionetworks.jira.com/browse/SNOW-336)
This is an addendum to #242. I had included a file for `CERTIFIEDQUIZQUESTION_LATEST`, but had accidentally used the DDL for the `USERPROFILE_LATEST` table instead. The `CERTIFIEDQUIZQUESTION_LATEST` in dev remained unchanged when we merged the PR.
I did it right this time.
[SNOW-336]: https://sagebionetworks.jira.com/browse/SNOW-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SNOW-336] Use snapshot_date in certifiedquizquestion_latest

---

admin/grants.sql

Samia does not have access to the GOVERNANCE role.
Grant Samia GOVERNANCE role.
N/A

Add governance role for user samia.ahmed@sagebase.org

---

.github/workflows/ci.yaml
sage/citations/V1.0.0__datacite_doi_table.sql
sage/schemachange-config.yml

Depends on #251 
Ticket: [SNOW-363](https://sagebionetworks.jira.com/browse/SNOW-363)
- SAGE.SCHEMACHANGE schema created
* This will be created automatically during deployment since `create-change-history-table` is `True` in our schemachange config.
- SAGE.SCHEMACHANGE.CHANGE_HISTORY table created
* ibid.
- Job added to ci.yaml for deployment to `SAGE` database
* The logic here mimics the jobs we already have for deploying to the synapse data warehouse. It references the new schemachange config file in the `sage` directory. The deployment will be performed by the `SAGE_ADMIN` role. The intention is that with future grants configured properly (as outlined in the design [here](https://sagebionetworks.jira.com/wiki/spaces/DPE/pages/4315217948/Analyst+Role+Hierarchy+and+Privilege+Management)), …

[SNOW-363] Synapse DOI table
