- synapse_data_warehouse/synapse_raw/tables/V2.0.0__create_certified_quiz_snapshot_tables_and_ingest_data.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.1.0__append_to_certified_quiz_snapshot_tasks.sql
The certified quiz record tables have been renamed to the snapshot tables
> [SNOW-19] Create certified quiz snapshot tables

- synapse_data_warehouse/synapse_raw/tasks/V2.6.0__fix_certified_quiz_question_tasks.sql
Currently the tasks copy the wrong columns.  One really irritating part of using schema change is that we don't edit one "task" object that changes over time.  So you have to go into snowflake to see the state of the object.
> [SNOW-32] Fix certified quiz question tasks

- synapse_data_warehouse/synapse_raw/tables/V2.7.0__create_initial_fileinventory_tables.sql
**Problem:**
File inventory snapshots from AWS needs to be ingested into snowflake
**Solution:**
Create initial ingestion into snowflake
> [SNOW-34] Add in file inventory data

- synapse_data_warehouse/synapse_raw/tasks/V2.7.1__append_to_fileinventory_task.sql
**Problem**
The file inventory table needs to be continually appended to
**Solution**
Add a snowflake task to continuously read from the external stage to append to the table
Depends on #14
> [SNOW-42] Append to file inventory task

- admin/grants.sql
**Problem**
`ALTER` and `DROP` table actions require ownership of the table.  Most created tables right now are by the SYSADMIN role.
**Solution**
Grant the DPE_service user access to the SYSADMIN role.  Eventually we will want to do an overall permissions scrub or transfer everything in snowflake to the DATA_ENGINEER role to keep things clean.
> [SNOW-43] Fix permissions for data engineer role

- synapse_data_warehouse/synapse_raw/tables/V2.8.0__reingest_userprofile_table.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.8.1__alter_user_profile_task.sql
**Problem**
Emails were obfuscated prior to snowflake being added as a subprocessor, now that snowflake is a subprocessor, we can adding those back into snowflake
**Solution**
1. Re-ingest userprofile snapshots (FORCE=TRUE to force ingest all the files in the s3 folder)
2. Alter userprofile snapshot task
> [SNOW-52] re-ingest userprofile tables

- synapse_data_warehouse/synapse_raw/tables/V2.9.0__reingest_nodesnapshot_table_and_add_effective_ar.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.9.1__update_nodesnapshot_task.sql
**Problem**
Prior to snowflake being a subprocessor, the node snapshot tables had filesnames obfuscated
**Solution**
1. truncate and reprocess the tables
2. since we are reprocessing, take this opportunity to add the effective AR column.
> [SNOW-53, SNOW-37] reprocess nodeshapshot and update nodesnapshot task

- synapse_data_warehouse/synapse_raw/tasks/V2.11.0__fix_filesnapshot_task.sql
**Problem**
Prior to snowflake being a subprocessor, filenames were hashed. Now, it doesn't need to be unhashed
**Solution**
Fix scheduled task
> [SNOW-54] Re-process filesnapshot tables

- synapse_data_warehouse/synapse_raw/tasks/V2.11.1__alter_filesnapshot_task.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.11.2__alter_filedownload_task.sql
**Problem**
- Prior to snowflake being a subprocessor, filenames were hashed. Now, it doesn't need to be unhashed
- Altered the wrong task, 
**Solution**
- Alter filesnapshot task without the hashing
- Re-push the filedownload task
> Alter filesnapshot task and fix filedownload task

- synapse_data_warehouse/synapse_raw/tables/V2.12.0__add_snapshot_date_to_fileinventory.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.12.1__add_snapshot_to_fileinventory_task.sql
**problem**
The fileinventory tables didn't have the snapshot date associated with them.  This is a problem because `last_modified_on` in the inventory tables do not correlate to a shift of the S3 object to different file inventories.
**Solution**
- add the snapshot_date as when the parquet file was created
- Add snapshot date in scheduled task
- reprocess data
> re-process fileinventory tables

- admin/integrations.sql
- synapse_data_warehouse/synapse/tables/V2.15.2__add_new_cert_columns.sql
- synapse_data_warehouse/synapse_raw/tables/V2.15.0__add_columns_to_cert.sql
- synapse_data_warehouse/synapse_raw/tasks/V2.15.1__add_new_cert_columns.sql
**Problem**
There are new columns being added that we want to incorporate from the parquet
**Solution**
Add the columns
**Bonus**
Add in file handle s3 bucket.  This was done in Snowsite to test the permissions
Depends on https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/pull/623
> [SNOW-72, SNOW-67] add revoke fields to certification quiz snapshot / latest

- analytics/find_disjointed_file_name_to_download_name.sql
**Problem:**
- Synapse allows an entity name to be disjointed from the name of the file. This can lead to some problems when the downloadAs name (The name of the file) overlaps with other files in the folder - and when the name of the FileEntity appears to be correct.
**Solution:**
- Adding in a small query I used to identify which Files in a specific folder had a DownloadAs name which did not match the name of the entity. We had used this to pass along information over to the collaborator to resolve the issue.
I also added a small script via this commit to the examples section that contains how to update all files in a folder to match the downloadAs to the name of the entity: https://github.com/Sage-Bionetworks/synapsePythonClient/commit/ed00ef506e5d5334c21728e4533e57a52124bd3e
> [SYNSD-893] Add query for disjointed name

- synapse_data_warehouse/synapse/dynamic_tables/V2.17.1__acl_latest.sql
**Problem**
We need a way to obtain the latest state of ACL for entities
**Solution**
- Use dynamic table to create said table
- parse out the resource access json and flatten it so that it is more usable across entities
> [SNOW-28] Add in ACL latest table

- sage/ip_lookup.py
**Problem**
It would be nice if we gathered the individual IP address information so we can make interesting analysis around cost and usage.
**Solution**
Leveraging a free API to extract the IP information and pushing it to a snowflake table.
Admittedly, the code is a bit hacky right now...
> Extract ip addresses

- synapse_data_warehouse/synapse/tables/V2.19.1__add_descriptions_to_teammember_latest.sql
This PR adds table and column comments for the `TEAMMEMBER_LATEST` table. This work and the syntax used is based on #38.
depends on #46
> [SNOW-80] Adds table and column comments for TEAMMEMBER_LATEST table

- synapse_data_warehouse/synapse/tables/V2.19.4__add_userprofile_latest_comments.sql
**Purpose:** Adds comments using descriptions from [datawarehouse-config.json](https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/blob/develop/src/main/resources/templates/datawarehouse/datawarehouse-config.json) to the `userprofile_latest` synapse table
**Testing:** I wasn't able to test my SQL script on a test database (when following these [contributing instructions](https://sagebionetworks.jira.com/wiki/spaces/DPE/pages/3109683240/Contributing)). [See comment on this here](https://sagebionetworks.jira.com/wiki/spaces/DPE/pages/3109683240/Contributing?focusedCommentId=3417931783)
> [SNOW-78] Add comments to userprofile_latest synapse table

- synapse_data_warehouse/synapse_raw/tables/R__create_projectsettingsnapshots_table.sql
- synapse_data_warehouse/synapse_raw/tables/R__projectsettingsnapshots_append_task.sql
Re-introducing the `projectsettingsnapshots` task script now that builds are working.
Tested the re-introduction of `LOCATIONS` column with dtype `ARRAY` on a test db (commit: https://github.com/Sage-Bionetworks/snowflake/pull/66/commits/1a860e7a1b22275a4e6de798d17ea877e248a9d8)
> [SNOW-33] reintroduce projectsettingsnapshots task

- synapse_data_warehouse/synapse_raw/tables/V2.20.0__ingest_into_projectsettingsnapshots.sql
This branch introduces an ingest script used to copy new data from staging into `projectsettingsnapshots`
testing the script on a test db ( some information is redacted for security ):
the files show up as expected in the table within my test db:
> [SNOW-33] New ingest to projectsettingsnapshots table

- admin/policies.sql
After adding jumpcloud and supporting multiple IDPs there was an awkward login period for snowflake
This avoids that by setting a `user_authentication_policy` on the account level with the opportunity to set specific user authentication policies for those that may want to test the jumpcloud login
Bonus: move most policies into the POLICY_DB so that policies don't get dropped on accident.
Note: these were run manually because there is currently no CI/CD to run auth policies
> Create authentication policies

- synapse_data_warehouse/synapse/dynamic_tables/V2.21.0__verificationsubmission_latest.sql
* The latest table for `verificationsubmissionsnapshots` does not exist in Snowflake.
* Following versioning best practices for Schemachange, we should initialize the dynamic table from a separate V script to mark its introduction into the system.
Associated with #81.
Add a V script to initialize `verificationsubmission_latest`
There are 19 unique submissions stored in the snapshots table, meaning there should be 19 total rows in the deduplicated latest table. The reason being that each submission can only be in 1 state - CREATED or UPDATED:
We verify that the V script generates a table with 19 rows:
We verify that the 19 unique IDs in the snapshots table matches the 19 unique IDs in the latest table:
( This query would produce results if there were any missing IDs from either table )
We …
> [SNOW-29] Initialize dynamic table: `verificationsubmission_latest`

- synapse_data_warehouse/synapse/dynamic_tables/R__populate_usergroup_latest.sql
- synapse_data_warehouse/synapse/dynamic_tables/V2.22.0__usergroup_latest.sql
Problem:
USERGROUP_LATEST table is not populated in the database.
Solution(WIP):
Add dynamic table USERGROUP_LATEST via a version script to pull deduplicated data from USERGROUPSNAPSHOT table. 
Test:
Tested in my personal stage data warehouse:
1. created `USERGROUP_LATEST` table and check for the ID `3576543` and get one row. 
2. Modified the base table `USERGROUPSNAPSHOT` by inserting two rows with newer `CHANGETIMESTAMP`
3. Refreshed the `USERGROUP_LATEST` table and got the updated row  for the ID `3576543`.
> [SNOW-27] add version script to populate usergroup_latest table

- synapse_data_warehouse/synapse/dynamic_tables/V2.24.0__projectsettings_latest.sql
About the data: The [Project Setting object](https://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/project/ProjectSetting.html) on Synapse is a project-based setting. The `projectsettingsnapshots` table contains records of all the states of a given project setting object. This includes when it was created, who it was created by, how it was last changed, and by whom, as well as other metadata like the setting type and what project this setting is for.
The latest table for `projectsettingsnapshots` does not exist in Snowflake. We should introduce a dynamic table that will reflect the latest state of a given project setting configuration on Synapse (i.e. whether it has been created, updated, or deleted, and all metadata which reflects this change)
A new Version script is created …
> [SNOW-82] Initialize dynamic table: `projectsetting_latest`

- synapse_data_warehouse/synapse_raw/tasks/V2.25.1__update_node_tasks.sql
I ran into the following error during the CI pipeline. I believe this is caused by not suspending the root task before trying to resume its dependents on this line: `SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('refresh_synapse_warehouse_s3_stage_task');`
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.15/x64/bin/schemachange", line 8, in <module>
schemachange version: 3.6.1
Using config file: synapse_data_warehouse/schemachange-config.yml
Using root folder /home/runner/work/snowflake/snowflake/synapse_data_warehouse
Using variables:
database_name: SYNAPSE_DATA_WAREHOUSE_DEV
stage_storage_integration: synapse_dev_warehouse_s3
stage_url: s3://dev.datawarehouse.sagebase.org/warehouse/
stack: dev
Using Snowflake account ***
sys.exit(main())
File …
```
> Fix SNOW-160 changes to dev

- synapse_data_warehouse/synapse_raw/tables/V2.25.2__refresh_node_snapshot.sql
I set up schemachange locally and ensured that by removing the scripting block I was able to successfully deploy the changes here (on a clone).
To limit the amount of data that needs to be loaded in the unlikely event we need to rollback/replay these changes, I changed the data being deleted/reloaded from all data from November 2024 onward to only data from November and December 2024. The side effect here is that any data from January 2025 onward which has been loaded into the table before we've replayed the `V2.25.*` scripts won't have its `version_history` data backfilled.
> [SNOW-160] Remove scripting block and reduce scope of refresh

- synapse_data_warehouse/synapse/dynamic_tables/V2.26.5__remove_ghost_assets_node_latest.sql
It was found that some nodes were incorrectly passing through the `CHANGE_TYPE != 'DELETE'` filter in the original query due to a misrepresentation of the latest `CHANGE_TYPE` for some deleted entities.
The reason for this misrepresentation is unclear, but is indirectly due to entities sitting in the trash can for 30 days leading to them being purged without a `DELETE` being recorded for this event. It also appears that this has something to do with the `PARENT_ID` of a node being changed, since the example we've seen this for had all their `CHANGE_TIMESTAMP`s locked on the date in which the parent entity was changed. As a result of this, all `CHANGE_TYPE`s were recorded with the same timestamp down to the second, resulting in `UPDATE` being the latest `CHANGE_TYPE` for these …
> [SNOW-175] `node_latest` dynamic table query update: Add stricter filter to remove deleted nodes

- synapse_data_warehouse/synapse_raw/tables/V2.27.0__document_aclsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.10__document_teammembersnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.11__document_teamsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.12__document_usergroupsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.13__document_userprofilesnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.14__document_verificationsubmissionsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.1__document_certifiedquiz.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.2__document_certifiedquizquestions.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.3__document_certifiedquizquestionsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.4__document_certifiedquizsnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.5__document_filedownload.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.6__document_fileinventory.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.7__document_filesnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.8__document_nodesnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.27.9__document_processedaccess.sql
Most of the bronze layer tables and their columns were missing documentation.
Add table and column comments for all the bronze layer tables that don't have. I used the [Synapse-Stack-Builder](https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/blob/f3b16e9c8cf0d919d136fd4e13d3490ac60220bf/src/main/resources/templates/datawarehouse/datawarehouse-config.json#L336) repo and the [Jira documentation](https://sagebionetworks.jira.com/wiki/spaces/DW/pages/3034775570/Raw+tables+in+Athena+Snowflake#File-Inventory) for column and table descriptions.
I ran all the scripts against the raw tables in [this clone](https://app.snowflake.com/mqzfhld/vp00034/#) and was able to confirm all table + column comments were applied.
> [SNOW-85] Document RAW tables

- synapse_data_warehouse/synapse_raw/tables/V2.28.0__add_is_two_factor_auth_enabled_to_userprofilesnapshots.sql
- synapse_data_warehouse/synapse_raw/tables/V2.28.1__update_userprofilesnapshots_task.sql
- synapse_data_warehouse/synapse_raw/tables/V2.28.2__refresh_userprofilesnapshots.sql
The parquet files now contain a new pieces of metadata `is_two_factor_auth_enabled` `industry` and `tos_agreements` but this metadata is not reflected in the current `userprofilesnapshots` table.
Following this SOP:
I tested the queries of all the scripts in `SYNAPSE_DATA_WAREHOUSE_JMEDINA.synapse_raw.userprofilesnapshot` so the results are available there.
I did a cross-check using the `id` column for the `userprofilesnapshot` in `synapse_data_warehouse_dev` and `synapse_data_warehouse_jmedina` and can confirm that all the IDs are accounted for:
The number of rows are also the same:
Let me know if you'd like me to share the worksheet where I ran these tests
> [SNOW-60,162,165] Add new columns to `userprofilesnapshots`

- synapse_data_warehouse/synapse_raw/tables/V2.28.1__update_userprofilesnapshots_task.sql
- synapse_data_warehouse/synapse_raw/tables/V2.28.2__refresh_userprofilesnapshots.sql
Instead of programmatically feeding the stage name, I had it hardcoded to `prod`, which broke when deploying to `dev`.
This PR patches that up in both the task and refresh scripts.
> [SNOW-60] Hotfix: Programmatically feed stage name

- synapse_data_warehouse/synapse_raw/tables/V2.28.2__refresh_userprofilesnapshots.sql
The refresh takes >10 mins to run for 400K rows in `dev` so it's worth bumping it up from xsmall->medium for the large refresh, since `prod` has >14m rows
The task will use xsmall since that's an incremental update
> [SNOW-60] Update the warehouse for the large refresh

- synapse_data_warehouse/synapse/dynamic_tables/V2.35.3__replace_node_latest.sql
We recently made a structural change to `nodesnapshots` by adding a new column, which resulted in the `node_latest` dynamic table breaking with the message in the screenshot below:
From the Snowflake devs:
> _When you add or remove a column to a table, if that column is unused, there will be no issues. If the column is used (in which case, a SELECT * is using the new column) this will result in the error you see._ 
The solution is to:
The query in this SQL script was run in `synapse_data_warehouse_jmedina` and changes can be viewed there when assuming the `SYSADMIN` role.
1. Confirm that the `project_storage_usage` exists ✔️ 
2. Confirm that the extra rows in the new `node_latest` are from the few days where the dynamic table was suspended
Query:
```
select *
from …
```
> [SNOW-222] Reintroduce `node_latest` dynamic table

- synapse_data_warehouse/synapse/dynamic_tables/V2.38.0__reintroduce_file_latest_dynamic_table.sql
- synapse_data_warehouse/synapse/dynamic_tables/V2.38.1__add_column_comments_to_new_file_latest.sql
Problem:
The original file_latest dynamic table does not have filter since the interpretation of `CHANGE_TYPE='DELETE'` vs `STATUS != "AVAILABLE"`. Platform team confirmed that `CHANGE_TYPE!='DELETE'` can be used to filter out file handles which have been deleted.
Solution:
> [SNOW-172] Add filter to file_latest and add comments 

- admin/policies/V1.10.0__initial_policy_document.sql
Snowflake has some idiosyncracies around running commands like `ALTER... POLICY...`. Since this affects statements in #148 which are attempting to alter account/user policies which are already set to those values, there's no value in jumping through the additional hoops Snowflake sets up to run these types of statements.
I left a comment which explains the reasoning for posterity:
```
-- A note on setting policies --
-- Policies can be set at the account or user level. Snowflake provides
-- slightly different mechanisms for updating each:
--
-- Account:
-- Normally, an account-level policy must be first UNSET before
-- we can SET that policy. Optionally, we can specify `... FORCE`
-- at the end of the ALTER statement to avoid needing to UNSET.
-- Since we've already set the account …
```
> [SNOW-239] Comment out redundant statements which set policies

- .github/workflows/ci.yaml
Currently, our CI job executes all its jobs at once, although the order in which those jobs runs may be important. I added `needs` fields to each job which should wait for the successful completion of another job before running. I also removed some unused, commented-out lines and reordered the jobs in the `ci.yaml` file itself so that they are ordered according to the order in which they will execute (this is why it looks like the changes are more drastic than they really are).
> [SNOW-224] Remove CI race condition

- admin/users.sql
Emails need to be quoted when passed to the IDENTIFIER function.
> [SNOW-241] hotfix: quote user identifier

- .github/workflows/test_with_clone.yaml
- synapse_data_warehouse/synapse_event/dynamic_tables/V2.51.1__update_filedownload_dynamic_table.sql
There are rows with nulls in ASSOCIATION_OBJECT_ID. 
Ticket: [SNOW-173](https://sagebionetworks.jira.com/browse/SNOW-173)
Add a filter to exclude these rows. 
Tested with production data that get the same # total_rows and # distinct_rows. 
[SNOW-173]: https://sagebionetworks.jira.com/browse/SNOW-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SNOW-173] exclude rows with nulls in ASSOCIATION_OBJECT_ID

- admin/grants.sql
- admin/users.sql
Karina Leal needs access to Snowsight so she can view the AD Usage Metrics dashboard.
Add Karina Leal as a `DATA_ANALYTICS` user.
N/A
> Add user Karina Leal

- synapse_data_warehouse/synapse_event/dynamic_tables/V2.53.0__node_event_table.sql
- synapse_data_warehouse/synapse_event/dynamic_tables/V2.56.0__add_objectdownload_event_dynamic_table.sql
The `node_event` table took ~40 minutes to build over production data during testing using the `compute_medium` warehouse. It was initially deployed to prod with the `compute_xsmall` warehouse, which caused the create command to timeout:
```
2025-06-12T23:29:05.834771Z [info     ] Applying change script         a_script_name=V2.53.0__node_event_table.sql script_version=2.53.0
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemachange/session/SnowflakeSession.py", line 326, in apply_change_script
self.execute_snowflake_query(query=script_content, logger=logger)
File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/schemachange/session/SnowflakeSession.py", line 116, in execute_snowflake_query
raise e
File …
```
> [0.8.0 hotfix] upgrade `node_event` warehouse to compute_medium

- synapse_data_warehouse/synapse_event/dynamic_tables/V2.62.0__file_event_table.sql
Ticket: [SNOW-296](https://sagebionetworks.jira.com/browse/SNOW-296)
Failure to deploy this change into `main` because it exceeded the `COMPUTE_XSMALL` warehouse time cap. [See here](https://github.com/Sage-Bionetworks/snowflake/actions/runs/16891795579) for more.
**Discussion**: The reason why we probably didn't see this issue when deploying to `dev` is because the dev stack data is much smaller in size. As a low priority ticket, we could write a set of guidelines for when we should upgrade to `COMPUTE_MEDIUM` based on query complexity, table size, etc.
Update the warehouse to `COMPUTE_MEDIUM` for this script.
CI/CD deployed a test db successfully, but this isn't entirely helpful since the clone is built off `dev` which isn't truly representative of the data volume we have in `prod` …
> [SNOW-296] Upgrade WH in V2.62.0__file_event_table.sql
